\hypertarget{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException}{}\section{edu.\+udel.\+cis.\+vsl.\+civl.\+model.\+I\+F.\+C\+I\+V\+L\+Internal\+Exception Class Reference}
\label{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException}\index{edu.\+udel.\+cis.\+vsl.\+civl.\+model.\+I\+F.\+C\+I\+V\+L\+Internal\+Exception@{edu.\+udel.\+cis.\+vsl.\+civl.\+model.\+I\+F.\+C\+I\+V\+L\+Internal\+Exception}}


\hyperlink{structA}{A} \hyperlink{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1CIVL}{C\+I\+V\+L} internal exception represents an error that is \char`\"{}not supposed to happen.\char`\"{} It can be used like an assertion, whenever you feel that something should always be true.  




Inheritance diagram for edu.\+udel.\+cis.\+vsl.\+civl.\+model.\+I\+F.\+C\+I\+V\+L\+Internal\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=215pt]{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for edu.\+udel.\+cis.\+vsl.\+civl.\+model.\+I\+F.\+C\+I\+V\+L\+Internal\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=330pt]{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException__coll__graph}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hypertarget{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException_a126e3b7d9f1be8fdc771829a88dd8888}{}{\bfseries C\+I\+V\+L\+Internal\+Exception} (String s, \hyperlink{interfaceedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLSource}{C\+I\+V\+L\+Source} \hyperlink{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLException_a29eba9d3541bcd7e2306404c6ece4d98}{source})\label{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException_a126e3b7d9f1be8fdc771829a88dd8888}

\item 
\hypertarget{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException_a40b4b207259f13c3b65926e79fb50971}{}{\bfseries C\+I\+V\+L\+Internal\+Exception} (String s, \hyperlink{interfaceedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1Sourceable}{Sourceable} sourceable)\label{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException_a40b4b207259f13c3b65926e79fb50971}

\item 
\hypertarget{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException_a0221b4ff13a4441e61816cf33bec5950}{}{\bfseries C\+I\+V\+L\+Internal\+Exception} (String s, Source \hyperlink{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLException_a29eba9d3541bcd7e2306404c6ece4d98}{source})\label{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1model_1_1IF_1_1CIVLInternalException_a0221b4ff13a4441e61816cf33bec5950}

\end{DoxyCompactItemize}
\subsection*{Additional Inherited Members}


\subsection{Detailed Description}
\hyperlink{structA}{A} \hyperlink{classedu_1_1udel_1_1cis_1_1vsl_1_1civl_1_1CIVL}{C\+I\+V\+L} internal exception represents an error that is \char`\"{}not supposed to happen.\char`\"{} It can be used like an assertion, whenever you feel that something should always be true. 

It is a runtime exception, so there is no need to declare or catch it. It will be thrown all the way up to main and reported. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/arnabd/workspace/civl/trunk/src/edu/udel/cis/vsl/civl/model/\+I\+F/C\+I\+V\+L\+Internal\+Exception.\+java\end{DoxyCompactItemize}
